RELATION = (
    "Compare a proposed change against one existing text unit.\n"
    "1) unit_topic: name the unit's main subject in a few words.\n"
    "2) relation:\n"
    "   - strong: this unit describes the very process, step, screen or field that the change adds a rule to, "
    "constrains or redefines. The change belongs in this unit EVEN IF the unit does not state the rule yet.\n"
    "   - medium: the unit only references or depends on that process, but mainly describes something else.\n"
    "   - none: unrelated subjects.\n"
    "3) justification: one or two sentences naming the concrete part of the unit and of the change that decide it.\n\n"
    "CHANGE:\n{change}\n\nUNIT:\n{unit}"
)
VERIFY = (
    "You are a skeptical reviewer. A previous pass claimed a proposed change belongs in this text unit.\n"
    "First, in objection, state the single strongest reason the change might NOT belong here.\n"
    "Then weigh that objection: it is only a stress test and does NOT by itself force a rejection.\n"
    "It is ENOUGH that the unit describes the process, step, screen or field the change governs; the unit need "
    "NOT already contain the rule, the validation logic, or be a detailed specification.\n"
    "Set agrees=false ONLY when the objection is a decisive disqualifier, that is one of:\n"
    "- the unit is only a generic precondition or boilerplate (e.g. 'User is authenticated', 'User has correct "
    "role assigned', 'Primary actor') with no feature description of its own;\n"
    "- the unit describes a different feature, screen or variant than the change governs (e.g. a different label "
    "format or document that merely shares vocabulary);\n"
    "- the link is purely generic and the unit does not describe the governed process.\n"
    "Otherwise set agrees=true. In particular, do NOT reject just because the rule is not yet stated, or because "
    "the unit is a process description rather than an explicit validation.\n\n"
    "CHANGE:\n{change}\n\nUNIT:\n{unit}\n\nCLAIMED JUSTIFICATION: {justification}"
)
MERGE = (
    "Apply the change to this unit, editing as little as possible. For each original sentence do exactly one thing:\n"
    "- keep it unchanged if the change does not affect it;\n"
    "- update it (reword only the part the change alters) if the change modifies what it states;\n"
    "- delete it if the change removes or invalidates what it states.\n"
    "Where the change introduces something new, insert it (verbatim when it stands on its own) at the point it "
    "applies. Keep every unaffected sentence in its original order.\n\n"
    "Examples (illustrative, unrelated domains):\n\n"
    "A) add: unit: 'Users can upload files. Uploaded files are scanned for viruses. A thumbnail is generated for "
    "images.'\n"
    "   change: 'Uploads are limited to 25 MB.'\n"
    "   merged_text: 'Users can upload files. Uploads are limited to 25 MB. Uploaded files are scanned for viruses. "
    "A thumbnail is generated for images.'\n"
    "   added: 'Uploads are limited to 25 MB.'\n\n"
    "B) update: unit: 'The gate opens at 8 AM. Visitors sign in at the desk. The gate closes at 6 PM.'\n"
    "   change: 'The gate now opens at 7 AM.'\n"
    "   merged_text: 'The gate opens at 7 AM. Visitors sign in at the desk. The gate closes at 6 PM.'\n"
    "   added: ''\n\n"
    "C) add a precondition without touching the flow: unit: 'A member first signs in and is asked to set a security "
    "question. They must answer it to continue.'\n"
    "   change: 'A member cannot sign in until an administrator has approved their account.'\n"
    "   merged_text: 'A member cannot sign in until an administrator has approved their account. A member first "
    "signs in and is asked to set a security question. They must answer it to continue.'\n"
    "   added: 'A member cannot sign in until an administrator has approved their account.'\n\n"
    "D) delete: unit: 'Users can pay by card. Cash payments are also accepted. Receipts are emailed.'\n"
    "   change: 'Cash payments are no longer accepted.'\n"
    "   merged_text: 'Users can pay by card. Receipts are emailed.'\n"
    "   added: ''\n\n"
    "CHANGE:\n{change}\n\nUNIT:\n{unit}"
)
