RELATION = (
    "Porównaj proponowaną zmianę z jedną istniejącą jednostką tekstu.\n"
    "1) unit_topic: nazwij główny temat jednostki w kilku słowach.\n"
    "2) relation:\n"
    "   - strong: ta jednostka opisuje sam proces, krok, ekran lub pole, do którego zmiana dodaje regułę, "
    "które ogranicza lub redefiniuje. Zmiana należy do tej jednostki, NAWET JEŚLI jednostka jeszcze tej reguły "
    "nie stwierdza.\n"
    "   - medium: jednostka jedynie odwołuje się do tego procesu lub od niego zależy, ale głównie opisuje coś innego.\n"
    "   - none: tematy bez związku.\n"
    "3) justification: jedno lub dwa zdania wskazujące konkretną część jednostki i zmiany, które o tym decydują.\n\n"
    "ZMIANA:\n{change}\n\nJEDNOSTKA:\n{unit}"
)
VERIFY = (
    "Jesteś sceptycznym recenzentem. Poprzedni przebieg stwierdził, że proponowana zmiana należy do tej jednostki "
    "tekstu.\n"
    "Najpierw, w polu objection, podaj jedyny najsilniejszy powód, dla którego zmiana może NIE należeć tutaj.\n"
    "Następnie rozważ ten zarzut: jest to jedynie test napięcia i sam w sobie NIE wymusza odrzucenia.\n"
    "WYSTARCZY, że jednostka opisuje proces, krok, ekran lub pole, którym zmiana rządzi; jednostka "
    "NIE musi już zawierać reguły, logiki walidacji ani być szczegółową specyfikacją.\n"
    "Ustaw agrees=false TYLKO wtedy, gdy zarzut jest rozstrzygającym dyskwalifikatorem, czyli jednym z:\n"
    "- jednostka jest tylko ogólnym warunkiem wstępnym lub szablonem (np. 'Użytkownik jest uwierzytelniony', "
    "'Użytkownik ma przypisaną poprawną rolę', 'Główny aktor') bez własnego opisu funkcji;\n"
    "- jednostka opisuje inną funkcję, ekran lub wariant niż ten, którym rządzi zmiana (np. inny format etykiety "
    "lub dokument, który jedynie dzieli słownictwo);\n"
    "- powiązanie jest czysto ogólne, a jednostka nie opisuje procesu, którego dotyczy zmiana.\n"
    "W przeciwnym razie ustaw agrees=true. W szczególności NIE odrzucaj tylko dlatego, że reguła nie jest jeszcze "
    "stwierdzona, ani dlatego, że jednostka jest opisem procesu, a nie jawną walidacją.\n\n"
    "ZMIANA:\n{change}\n\nJEDNOSTKA:\n{unit}\n\nDEKLAROWANE UZASADNIENIE: {justification}"
)
MERGE = (
    "Zastosuj zmianę do tej jednostki, edytując jak najmniej. Dla każdego oryginalnego zdania zrób dokładnie jedną "
    "rzecz:\n"
    "- zostaw je bez zmian, jeśli zmiana go nie dotyczy;\n"
    "- zaktualizuj je (przeredaguj tylko tę część, którą zmiana modyfikuje), jeśli zmiana modyfikuje to, co ono "
    "stwierdza;\n"
    "- usuń je, jeśli zmiana usuwa lub unieważnia to, co ono stwierdza.\n"
    "Tam, gdzie zmiana wprowadza coś nowego, wstaw to (dosłownie, gdy stanowi samodzielną całość) w miejscu, w "
    "którym ma zastosowanie. Zachowaj każde niezmienione zdanie w jego oryginalnej kolejności.\n\n"
    "Przykłady (poglądowe, z niepowiązanych dziedzin):\n\n"
    "A) dodanie: jednostka: 'Użytkownicy mogą przesyłać pliki. Przesłane pliki są skanowane w poszukiwaniu wirusów. "
    "Dla obrazów generowana jest miniatura.'\n"
    "   zmiana: 'Przesyłane pliki są ograniczone do 25 MB.'\n"
    "   merged_text: 'Użytkownicy mogą przesyłać pliki. Przesyłane pliki są ograniczone do 25 MB. Przesłane pliki "
    "są skanowane w poszukiwaniu wirusów. Dla obrazów generowana jest miniatura.'\n"
    "   added: 'Przesyłane pliki są ograniczone do 25 MB.'\n\n"
    "B) aktualizacja: jednostka: 'Brama otwiera się o 8:00. Odwiedzający meldują się w recepcji. Brama zamyka się "
    "o 18:00.'\n"
    "   zmiana: 'Brama otwiera się teraz o 7:00.'\n"
    "   merged_text: 'Brama otwiera się o 7:00. Odwiedzający meldują się w recepcji. Brama zamyka się o 18:00.'\n"
    "   added: ''\n\n"
    "C) dodanie warunku wstępnego bez naruszania przebiegu: jednostka: 'Członek najpierw się loguje i jest proszony "
    "o ustawienie pytania zabezpieczającego. Musi na nie odpowiedzieć, aby kontynuować.'\n"
    "   zmiana: 'Członek nie może się zalogować, dopóki administrator nie zatwierdzi jego konta.'\n"
    "   merged_text: 'Członek nie może się zalogować, dopóki administrator nie zatwierdzi jego konta. Członek "
    "najpierw się loguje i jest proszony o ustawienie pytania zabezpieczającego. Musi na nie odpowiedzieć, aby "
    "kontynuować.'\n"
    "   added: 'Członek nie może się zalogować, dopóki administrator nie zatwierdzi jego konta.'\n\n"
    "D) usunięcie: jednostka: 'Użytkownicy mogą płacić kartą. Akceptowane są także płatności gotówką. Paragony są "
    "wysyłane e-mailem.'\n"
    "   zmiana: 'Płatności gotówką nie są już akceptowane.'\n"
    "   merged_text: 'Użytkownicy mogą płacić kartą. Paragony są wysyłane e-mailem.'\n"
    "   added: ''\n\n"
    "ZMIANA:\n{change}\n\nJEDNOSTKA:\n{unit}"
)
